import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <script dangerouslySetInnerHTML={{
        __html: `(function () {
          var d = function d(a) {
              for (var e = arguments.length, n = new Array(e > 1 ? e - 1 : 0), i = 1; i < e; i++)
                  n[i - 1] = arguments[i];
              d.queue.push([a].concat(n))
          };
          d.queue = [], window.dadk = window.dadk || d;
          var a = document.createElement("script");
          a.src = "undefined" != typeof URLSearchParams ? 'https://unpkg.com/@dcard/web-ad-tracking-sdk/build/dadk.iife.js' : 'https://unpkg.com/@dcard/web-ad-tracking-sdk/build/outdated-dadk.iife.js',
              document.head.appendChild(a),
              window.dadk("init", "GBZ-aaBUuD06UpTkOJzgC"),
              window.dadk("track", "PageView");
      })();`
      }}></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
